<a href="https://colab.research.google.com/github/PrathamLaddha/XRP1/blob/main/XRPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
!pip install propythia
!pip install biopython
!pip install mdtraj
!pip install transformers sentencepiece torch

Collecting propythia
  Downloading propythia-3.0.2-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.5/44.5 kB 1.6 MB/s eta 0:00:00
Downloading propythia-3.0.2-py3-none-any.whl (4.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 36.5 MB/s eta 0:00:00
Installing collected packages: propythia
Successfully installed propythia-3.0.2
Collecting biopython
  Downloading biopython-1.85-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)
Downloading biopython-1.85-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 25.2 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.85
Collecting mdtraj
  Downloading mdtraj-1.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.6 kB)
Requirement already satisfied: numpy<3,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from mdtraj) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from mdtraj) (1.16.2)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from mdtraj) (3.2.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from mdtraj) (25.0)
Downloading mdtraj-1.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 49.4 MB/s eta 0:00:00
Installing collected packages: mdtraj
Successfully installed mdtraj-1.11.0
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)

In [30]:
from Bio.Seq import Seq
from Bio.SeqUtils.ProtParam import ProteinAnalysis
import mdtraj as md
import torch
from transformers import T5Tokenizer
from transformers import T5EncoderModel

In [28]:
rpi = pd.read_csv("/content/drive/MyDrive/XRPI/RPI2825.csv")

In [29]:
rpi.head()

,type,protein_seq,rna_seq
0,nonribo,HSFLSPDAQVLVLAISSHPLPTLAAFLASRRDELLRADITSLLKAL...,GUAUUCUUUAAUUAUUUC
1,nonribo,MKVEEILEKALELVIPDEEEVRKGREAEEELRRRLDELGVEYVFVG...,GGCCCGGGGCGGUUCGAUUCCGCCCUGGGCCACCA
2,nonribo,GSHMTSPFKLPDESPSWTEWRLHNDETNSNQDNPLGFKESWGFGKV...,CCGCCGCCGCCGCCGCCGCG
3,nonribo,GSGFLYGGRGMHGFCLNRKRRTAAGPRRLQGQDLVRLVFFEGLPYL...,GGAACGCCGCGGUCAGCUCGGCUGCUGCGAAGAGUUCGUCUCUGUU...
4,nonribo,FDLNDFLEQLRQMKNMGGMASLMGKLPGMGQIPDNVKSQMDDKVLV...,GGUGCUGUUUACCAGGUCAGGUCCGAAAGGAAGCAGCCAAGGCAGUGCC

Getting molecular weight

In [39]:
def mol_wt(seq):
  cleaned_seq = str(seq).replace("X", "")
  return ProteinAnalysis(cleaned_seq).molecular_weight()
rpi['mol_wt'] = rpi['protein_seq'].apply(mol_wt)
rpi.head()

,type,protein_seq,rna_seq,mol_wt
0,nonribo,HSFLSPDAQVLVLAISSHPLPTLAAFLASRRDELLRADITSLLKAL...,GUAUUCUUUAAUUAUUUC,79199.8872
1,nonribo,MKVEEILEKALELVIPDEEEVRKGREAEEELRRRLDELGVEYVFVG...,GGCCCGGGGCGGUUCGAUUCCGCCCUGGGCCACCA,51384.4998
2,nonribo,GSHMTSPFKLPDESPSWTEWRLHNDETNSNQDNPLGFKESWGFGKV...,CCGCCGCCGCCGCCGCCGCG,14494.0435
3,nonribo,GSGFLYGGRGMHGFCLNRKRRTAAGPRRLQGQDLVRLVFFEGLPYL...,GGAACGCCGCGGUCAGCUCGGCUGCUGCGAAGAGUUCGUCUCUGUU...,29937.6884
4,nonribo,FDLNDFLEQLRQMKNMGGMASLMGKLPGMGQIPDNVKSQMDDKVLV...,GGUGCUGUUUACCAGGUCAGGUCCGAAAGGAAGCAGCCAAGGCAGUGCC,11707.8607